nelmio_api_doc:
    cache: []
    documentation:
        info:
            title: Pet API
            description: This is an awesome app!
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/pet